# Generated by Django 4.2.19 on 2025-03-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(choices=[('bsi', 'Bank Syariah Indonesia'), ('bjb', 'Bank Jabar Banten Syariah'), ('midtrans', 'Midtrans')], max_length=10),
        ),
    ]
