# Generated by Django 4.2.19 on 2025-03-12 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_anonymous_donor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
