# Generated by Django 4.2.19 on 2025-03-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_is_anonymous_donor_remove_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
