# Generated by Django 4.2.19 on 2025-03-05 00:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='update',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
