# Generated by Django 4.2.19 on 2025-03-19 06:37

from django.db import migrations, models
from django.utils.text import slugify

def generate_slugs(apps, schema_editor):
    Campaign = apps.get_model('campaigns', 'Campaign')  # Ganti 'nama_aplikasi_anda' dengan nama aplikasi Anda
    for campaign in Campaign.objects.all():
        if not campaign.slug:
            campaign.slug = slugify(campaign.title)
            campaign.save()

class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_description_alter_update_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='slug',
            field=models.SlugField(unique=True, blank=True, null=True),  # Izinkan null sementara
        ),
        migrations.RunPython(generate_slugs),  # Jalankan fungsi untuk mengisi slug
        migrations.AlterField(
            model_name='campaign',
            name='slug',
            field=models.SlugField(unique=True, blank=False),  # Setel `null=False` dan `blank=False`
        ),
    ]
