# Generated by Django 4.2.19 on 2025-03-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('islam', 'Agama Islam'), ('it', 'Programming & Development'), ('teknik', 'Engineering'), ('bisnis', 'Business & Entrepreneurship'), ('kreatif', 'Design & Creativity'), ('personal', 'Personal Development'), ('kesehatan', 'Health & Lifestyle'), ('akademik', 'Academics & Test Prep')], max_length=20),
        ),
    ]
