# Generated by Django 4.2.19 on 2025-03-12 08:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_m', models.CharField(blank=True, max_length=10, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('name_full', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('l', 'Laki-laki'), ('p', 'Perempuan')], max_length=1, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('bn', 'Belum Nikah'), ('n', 'Nikah'), ('d', 'Duda'), ('j', 'Janda')], max_length=10, null=True)),
                ('segment', models.CharField(blank=True, choices=[('mahasiswa', 'Mahasiswa'), ('pelajar', 'Pelajar'), ('santri', 'Santri'), ('karyawan', 'Karyawan'), ('umum', 'Umum')], max_length=10, null=True)),
                ('study_level', models.CharField(blank=True, choices=[('sd', 'Sekolah Dasar atau Setara'), ('smp', 'Sekolah Menengah Pertama atau Setara'), ('sma', 'Sekolah Menengah Atas / Kejuruan atau Setara'), ('s1', 'Sarjana'), ('s2', 'Magister'), ('s3', 'Doktor')], max_length=100, null=True)),
                ('study_campus', models.CharField(blank=True, max_length=100, null=True)),
                ('study_faculty', models.CharField(blank=True, max_length=100, null=True)),
                ('study_department', models.CharField(blank=True, max_length=100, null=True)),
                ('study_program', models.CharField(blank=True, max_length=100, null=True)),
                ('study_semester', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)])),
                ('study_start_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)])),
                ('study_finish_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)])),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('job', models.CharField(blank=True, choices=[('mahasiswa', 'Mahasiswa'), ('asn', 'Aparatur Sipil Negara'), ('karyawan_swasta', 'Karyawan Swasta'), ('guru', 'Guru'), ('dosen', 'Dosen'), ('dokter', 'Dokter'), ('perawat', 'Perawat'), ('apoteker', 'Apoteker'), ('programmer', 'Programmer'), ('data_scientist', 'Data Scientist'), ('desainer_grafis', 'Desainer Grafis'), ('marketing', 'Marketing'), ('hrd', 'HRD (Human Resources Department)'), ('akuntan', 'Akuntan'), ('konsultan', 'Konsultan'), ('arsitek', 'Arsitek'), ('insinyur', 'Insinyur'), ('peneliti', 'Peneliti'), ('jurnalis', 'Jurnalis'), ('penulis', 'Penulis'), ('penerjemah', 'Penerjemah'), ('pilot', 'Pilot'), ('pramugari', 'Pramugari'), ('chef', 'Chef'), ('pengusaha', 'Pengusaha'), ('petani', 'Petani'), ('nelayan', 'Nelayan'), ('pengrajin', 'Pengrajin'), ('teknisi', 'Teknisi'), ('seniman', 'Seniman'), ('musisi', 'Musisi'), ('atlet', 'Atlet'), ('polisi', 'Polisi'), ('tentara', 'Tentara'), ('pengacara', 'Pengacara'), ('notaris', 'Notaris'), ('psikolog', 'Psikolog'), ('sopir', 'Sopir'), ('kurir', 'Kurir'), ('barista', 'Barista'), ('freelancer', 'Freelancer')], max_length=100, null=True)),
                ('work_field', models.CharField(blank=True, choices=[('pendidikan', 'Pendidikan'), ('kesehatan', 'Kesehatan'), ('ekobis', 'Ekonomi Bisnis'), ('agrotek', 'Agrotek'), ('herbal', 'Herbal-Farmasi'), ('it', 'IT'), ('manufaktur', 'Manufaktur'), ('energi', 'Energi-Mineral'), ('sains', 'Sains'), ('teknologi', 'Teknologi'), ('polhuk', 'Politik-Hukum'), ('humaniora', 'Humaniora'), ('media', 'Media-Literasi'), ('sejarah', 'Sejarah')], max_length=100, null=True)),
                ('work_institution', models.CharField(blank=True, max_length=100, null=True)),
                ('work_position', models.CharField(blank=True, max_length=100, null=True)),
                ('work_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('address_latitude', models.FloatField(blank=True, null=True)),
                ('address_longitude', models.FloatField(blank=True, null=True)),
                ('address_province', models.CharField(blank=True, choices=[('aceh', 'Aceh'), ('sumatera_utara', 'Sumatera Utara'), ('sumatera_barat', 'Sumatera Barat'), ('riau', 'Riau'), ('jambi', 'Jambi'), ('sumatera_selatan', 'Sumatera Selatan'), ('bengkulu', 'Bengkulu'), ('lampung', 'Lampung'), ('kepulauan_bangka_belitung', 'Kepulauan Bangka Belitung'), ('kepulauan_riau', 'Kepulauan Riau'), ('dki_jakarta', 'DKI Jakarta'), ('jawa_barat', 'Jawa Barat'), ('jawa_tengah', 'Jawa Tengah'), ('di_yogyakarta', 'DI Yogyakarta'), ('jawa_timur', 'Jawa Timur'), ('banten', 'Banten'), ('bali', 'Bali'), ('nusa_tenggara_barat', 'Nusa Tenggara Barat'), ('nusa_tenggara_timur', 'Nusa Tenggara Timur'), ('kalimantan_barat', 'Kalimantan Barat'), ('kalimantan_tengah', 'Kalimantan Tengah'), ('kalimantan_selatan', 'Kalimantan Selatan'), ('kalimantan_timur', 'Kalimantan Timur'), ('kalimantan_utara', 'Kalimantan Utara'), ('sulawesi_utara', 'Sulawesi Utara'), ('sulawesi_tengah', 'Sulawesi Tengah'), ('sulawesi_selatan', 'Sulawesi Selatan'), ('sulawesi_tenggara', 'Sulawesi Tenggara'), ('gorontalo', 'Gorontalo'), ('sulawesi_barat', 'Sulawesi Barat'), ('maluku', 'Maluku'), ('maluku_utara', 'Maluku Utara'), ('papua', 'Papua'), ('papua_barat', 'Papua Barat')], max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
