# Generated by Django 4.2.19 on 2025-03-03 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('makanan', 'Produk Makanan'), ('minuman', 'Produk Minuman'), ('obat', 'Produk Obat obatan'), ('elektronik', 'Barang Elektronik'), ('peralatan', 'Peralatan Pertukangan'), ('gadget', 'Gadget'), ('iftar', 'Berbagi Iftar'), ('jumat', 'Jumat Berkah')], max_length=20)),
                ('thumbnail', models.ImageField(upload_to='product_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
