# Generated by Django 4.2.19 on 2025-03-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'kg'), ('m', 'meter'), ('pcs', 'butir'), ('pack', 'bungkus'), ('unit', 'unit'), ('set', 'set'), ('package', 'paket')], default='kg', max_length=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('sembako', 'Bahan Makanan'), ('makan-minum', 'Makanan & Minuman'), ('obat', 'Produk Obat obatan'), ('elektronik', 'Barang Elektronik'), ('peralatan', 'Peralatan Pertukangan'), ('gadget', 'Gadget')], max_length=20),
        ),
    ]
