# Generated by Django 4.2.19 on 2025-03-21 04:17

from django.db import migrations, models
from django.utils.text import slugify

def generate_slugs(apps, schema_editor):
    Product = apps.get_model('products', 'Product')  # Ganti 'nama_aplikasi_anda' dengan nama aplikasi Anda
    for product in Product.objects.all():
        if not product.slug:
            product.slug = slugify(product.title)
            product.save()

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_stock_product_unit_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, null=True),
        ),
        migrations.RunPython(generate_slugs),  # Jalankan fungsi untuk mengisi slug
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True, blank=False),  # Setel `null=False` dan `blank=False`
        ),        
    ]
